Presentation.WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.WebApplication.Controllers
{
    public class HomeController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }
    }
}

Presentation.WebApplication/Controllers/WereHouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Presentation.WebApplication.ServiceWereHouse;

namespace Presentation.WebApplication.Controllers
{
    public class WereHouseController : Controller
    {
        private readonly IServiceWereHouse _serviceWereHouse;

        public WereHouseController(IServiceWereHouse serviceWereHouse) 
        {
            _serviceWereHouse = serviceWereHouse;
        }

        public ActionResult WereHouse()
        {
            return View();
        }


        public ActionResult Products()
        {
            var products = _serviceWereHouse.GetAllProducts();

            return View();
        }

        [HttpGet]
        public JsonResult productos()
        {
            var products = _serviceWereHouse.GetAllProducts().ToList();

            return Json(products, JsonRequestBehavior.AllowGet);
        }
       
    }
}

Presentation.WebApplication/Views/Shared/_Footer.cshtml
<footer>
    <p>&copy @DateTime.Now.Year All Rights Reserved | Design by Pierre</p>
</footer>

Presentation.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app ="Application">
<head>
    <title>:: Portal Comercial ::</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    @Styles.Render("~/bundles/bootstrap")
    @Styles.Render("~/bundles/theme")
    @Styles.Render("~/bundles/dynatable")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrapjs")
    @Scripts.Render("~/bundles/angularjs")
    @Scripts.Render("~/bundles/dynatablejs")

    <script>

        window.rootPath = '@Url.Content("~")';

    </script>
</head>
<body class="sticky-header left-side-collapsed">
    <section>


        <!--Menu-->
        @Html.Partial("~/Views/Shared/_Menu.cshtml")
        <!--Menu-->
        <!--Content-->
        <div class="main-content" ">
            <!-- header-starts -->
            <div class="header-section">
                <!--notification menu -->
                @Html.Partial("~/Views/Shared/_MenuNotification.cshtml")
                <!--notification menu -->
            </div>
            <!-- //header-ends -->
            <div id="page-wrapper">
                @RenderBody()
            </div>

        </div>
        <!--Content-->
        <!--footer-->
        @Html.Partial("~/Views/Shared/_Footer.cshtml")
        <!--footer-->

    </section>



    @Scripts.Render("~/bundles/themejs")

    @RenderSection("scripts", required: false)
</body>
</html>

Presentation.WebApplication/Views/Shared/_Menu.cshtml
<!-- left side start-->
<div class="left-side sticky-left-side">

    <!--logo and iconic logo start-->
    <div class="logo">
    </div>
    <div class="logo-icon text-center">
        <a alt="Home"><i class="lnr lnr-home"></i> </a>
    </div>

    <!--logo and iconic logo end-->
    <div class="left-side-inner">

        <!--sidebar nav start-->
        <ul class="nav nav-pills nav-stacked custom-nav">
            <li class="active"><a href="index.html"><i class="lnr lnr-power-switch"></i><span>Dashboard</span></a></li>
            <li class="menu-list">
                <a href="#">
                    <i class="lnr lnr-cog"></i>
                    <span>Components</span>
                </a>
                <ul class="sub-menu-list">
                    <li><a href="grids.html">Grids</a> </li>
                    <li><a href="widgets.html">Widgets</a></li>
                </ul>
            </li>
            <li class="menu-list">
                <a><i class="lnr lnr-envelope"></i> <span>ALMACEN</span></a>
                <ul class="sub-menu-list">
                    <li>@Html.ActionLink("Productos", "WereHouse", "WereHouse")</li>
                </ul>
            </li>
            <li class="menu-list">
                <a href="#"><i class="lnr lnr-indent-increase"></i> <span>Menu Levels</span></a>
                <ul class="sub-menu-list">
                    <li><a href="charts.html">Basic Charts</a> </li>
                </ul>
            </li>
            <li><a href="codes.html"><i class="lnr lnr-pencil"></i> <span>Typography</span></a></li>
            <li><a href="media.html"><i class="lnr lnr-select"></i> <span>Media Css</span></a></li>
            <li class="menu-list">
                <a href="#"><i class="lnr lnr-book"></i>  <span>Pages</span></a>
                <ul class="sub-menu-list">
                    <li><a href="sign-in.html">Sign In</a> </li>
                    <li><a href="sign-up.html">Sign Up</a></li>
                    <li><a href="blank_page.html">Blank Page</a></li>
                </ul>
            </li>
        </ul>
        <!--sidebar nav end-->
    </div>
</div>

Presentation.WebApplication/Views/Shared/_MenuNotification.cshtml
<div class="menu-right">
    <div class="user-panel-top">
        <div class="profile_details_left">
            <ul class="nofitications-dropdown">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <div class="notification_header">
                                <h3>You have 3 new messages</h3>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="images/1.png" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor sit amet</p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li class="odd">
                            <a href="#">
                                <div class="user_img"><img src="images/1.png" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor sit amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="images/1.png" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor sit amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <div class="notification_bottom">
                                <a href="#">See all messages</a>
                            </div>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell"></i><span class="badge blue">3</span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="notification_header">
                                <h3>You have 3 new notification</h3>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="images/1.png" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor sit amet</p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li class="odd">
                            <a href="#">
                                <div class="user_img"><img src="images/1.png" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor sit amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="images/1.png" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor sit amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <div class="notification_bottom">
                                <a href="#">See all notification</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i><span class="badge blue1">22</span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="notification_header">
                                <h3>You have 8 pending task</h3>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Database update</span><span class="percentage">40%</span>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="progress progress-striped active">
                                    <div class="bar yellow" style="width:40%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Dashboard done</span><span class="percentage">90%</span>
                                    <div class="clearfix"></div>
                                </div>

                                <div class="progress progress-striped active">
                                    <div class="bar green" style="width:90%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Mobile App</span><span class="percentage">33%</span>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="progress progress-striped active">
                                    <div class="bar red" style="width: 33%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Issues fixed</span><span class="percentage">80%</span>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="progress progress-striped active">
                                    <div class="bar  blue" style="width: 80%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <div class="notification_bottom">
                                <a href="#">See all pending task</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <div class="clearfix"></div>
            </ul>
        </div>
        <div class="profile_details">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span style="background:url(images/1.jpg) no-repeat center"> </span>
                            <div class="user-name">
                                <p>Michael<span>Administrator</span></p>
                            </div>
                            <i class="lnr lnr-chevron-down"></i>
                            <i class="lnr lnr-chevron-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>
                        <li> <a href="#"><i class="fa fa-user"></i>Profile</a> </li>
                        <li> <a href="sign-up.html"><i class="fa fa-sign-out"></i> Logout</a> </li>
                    </ul>
                </li>
                <div class="clearfix"> </div>
            </ul>
        </div>

        <div class="clearfix"></div>
    </div>
</div>

Presentation.WebApplication/Views/WereHouse/Products.cshtml
@Scripts.Render("~/bundles/Productjs")


<div class="panel panel-default" ng-controller="ProductController">
    <div class="panel-heading">
        <h3>Almacen > Productos</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-2">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Codigo" />
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Descripciòn" />
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <select class="form-control btn btn-default">
                        <option>ESTADO</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="pull-right">
                    <button type="button" class="btn btn-info customButtom" aria-label="Left Align">
                        <span class="fa fa-search fa-lg" aria-hidden="true"></span>
                        Buscar
                    </button>
                </div>
            </div>
        </div>
        <div class="row">
            <hr />
        </div>
        <div class="row">
            <div class="col-md-10">
                <div id="container">
                    <table id="table-pruebita" class="display compact custom" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Codigo</th>
                                <th>Descripcion</th>
                                <th>Tipo</th>
                                <th>Marca</th>
                                <th>Fecha Registro</th>
                                <th>Estado</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <div class="col-md-2">
                <center>
                    <div class="form-group">
                        <button type="button" class="btn btn-info customButtom" aria-label="Left Align">
                            <span class="fa fa-plus fa-lg" aria-hidden="true"></span>
                            Nuevo Producto
                        </button>
                    </div>
                </center>
            </div>
        </div>

    </div>
</div>

Presentation.WebApplication/Views/WereHouse/WereHouse.cshtml
@Html.Partial("Products")

<div class="panel panel-default">
    <div class="panel-body">
        <h1>asdasd</h1>
    </div>
</div>